buyer_balance = 70
if (buyer_balance >= 25):
    print ("you have a new book")
    buyer_balance = buyer_balance - 25
    print (("Your balance is"), (buyer_balance))
else:
    print ("You don't have enough money, sorry!!")
    


a = 5 + 3
if a == 7:
    print('a is 7')
else:
    print('a is not 7')    
    
    
age = 15
if age>=18:
    print('older')

else:
    print('not older')
    

edad = 67
if edad>=18:
    print('mayor de edad')
else:
    print('menor de edad')    
    
    
a = 2 + 4
if a == 4: 
    print ("A is Four") 
elif a == 5:
    print ("A is Five") 
elif a == 6:
    print ("A is six")
else:
    print ("no condition") 
    
    
a = 2 + 67
if a == 4: 
    print ("A is Four") 
elif a == 5:
    print ("A is Five") 
elif a == 6:
    print ("A is six")
else:
    print ("no condition") 
    










